# Generated by Django 4.2.2 on 2023-06-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_level_user_level'),
        ('TimeTable', '0003_remove_user_groups_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.level'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.level'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
