# Generated by Django 4.2.2 on 2023-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0004_alter_subject_level_alter_timetable_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
