# Generated by Django 4.2.2 on 2023-06-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0005_classroom_description_classroom_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='start_end',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='week',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
