# Generated by Django 4.2.2 on 2023-06-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTable', '0006_rename_start_end_timetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='week',
            field=models.IntegerField(null=True),
        ),
    ]
