# Generated by Django 4.2.2 on 2023-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_level_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
